version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - circleci-user

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtualenv'
          command: |
            uv venv --python 3.12 ~/.virtualenvs/target-stitch
            source ~/.virtualenvs/target-stitch/bin/activate
            uv pip install -U setuptools pytest
            uv pip install -e .[dev]
      - run:
          name: 'pylint'
          command: |
            source ~/.virtualenvs/target-stitch/bin/activate
            pylint target_stitch "--extension-pkg-whitelist=ciso8601" --max-positional-arguments=8 -d 'global-variable-not-assigned, consider-using-generator, broad-exception-raised, unused-argument'
      - run:
          name: 'Run tests'
          command: |
            # Need to re-activate the virtualenv
            source ~/.virtualenvs/target-stitch/bin/activate
            pytest tests/activate_version_tests.py
            pytest --ignore=activate_version_tests.py
